### ISSUE TITLE
Why on earth the functions are suspend?

### ISSUE THREAD

**Issue by nikolamin** [michaeltroger/latin-to-cyrillic#2]
I don't see any good reason to make `latinToCyrillic` and `cyrillicToLatin` suspend fun. It makes them useless in certain cases. There is nothing that blocks in their implementation. The caller method can take care of asynchronous execution if needed.

btw. you can put some fancy extension functions:

`fun String.cyrillicToLatin(text: String, alphabet: Alphabet = DEFAULT_ALPHABET)`
`fun String.cyrillicToLatinMk(text: String)`
`fun String.cyrillicToLatinMkIso9(text: String)`

**Comment by michaeltroger** [comment]
Hi,
it's a good practise to make CPU expensive tasks suspendible in Kotlin apps.
Especially on Android but also on other platforms it's a bad practise to perform expensive operations on the UI thread.
While I agree that it's not an issue for short words/sentences, the app using it will lack on longer texts/articles.
Suspending allows you to e.g. show a loading indicator while the process is ongoing.

And if you really don't want to handle async behavior you can can call the methods inside `runBlocking {}`.

Regarding extension functions I ask you to create the ones you need yourself. I want to keep the public API as minimal as possible. Personally I would not  recommend to expose extension  functions on Strings in a large scope. If you really want extension functions on a basic type like String, then I would recommend to define them private to the class where they are needed.
